name: UKMCAB E2E TESTS
run-name: ${{ github.actor }} is running GitHub Actions for UKMCAB e2e tests ðŸš€
on: [push]
jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create cypress.env.json with secret config values stored in Github
        run: |
          echo '${{ secrets.E2E_ENV_VARS }}' > cypress.env.json
      - name: Cypress Run
        uses: cypress-io/github-action@v5.0.2
        with:
          browser: chrome